// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package citation.comm;


public class GetDMVResultAsXML {
    protected java.lang.String _license;
    
    public GetDMVResultAsXML() {
    }
    
    public GetDMVResultAsXML(java.lang.String _license) {
        this._license = _license;
    }
    
    public java.lang.String get_license() {
        return _license;
    }
    
    public void set_license(java.lang.String _license) {
        this._license = _license;
    }
}
