// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package citation.comm;


public class OpenCitationResponse {
    protected int openCitationReturn;
    
    public OpenCitationResponse() {
    }
    
    public OpenCitationResponse(int openCitationReturn) {
        this.openCitationReturn = openCitationReturn;
    }
    
    public int getOpenCitationReturn() {
        return openCitationReturn;
    }
    
    public void setOpenCitationReturn(int openCitationReturn) {
        this.openCitationReturn = openCitationReturn;
    }
}
