// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package citation.comm;


public class PostCitationEntryResponse {
    protected int postCitationEntryReturn;
    
    public PostCitationEntryResponse() {
    }
    
    public PostCitationEntryResponse(int postCitationEntryReturn) {
        this.postCitationEntryReturn = postCitationEntryReturn;
    }
    
    public int getPostCitationEntryReturn() {
        return postCitationEntryReturn;
    }
    
    public void setPostCitationEntryReturn(int postCitationEntryReturn) {
        this.postCitationEntryReturn = postCitationEntryReturn;
    }
}
