// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package citation.comm;


public class PostCitationAsXML {
    protected java.lang.String xml;
    
    public PostCitationAsXML() {
    }
    
    public PostCitationAsXML(java.lang.String xml) {
        this.xml = xml;
    }
    
    public java.lang.String getXml() {
        return xml;
    }
    
    public void setXml(java.lang.String xml) {
        this.xml = xml;
    }
}
