// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package citation.comm;


public class PostString {
    protected java.lang.String s;
    
    public PostString() {
    }
    
    public PostString(java.lang.String s) {
        this.s = s;
    }
    
    public java.lang.String getS() {
        return s;
    }
    
    public void setS(java.lang.String s) {
        this.s = s;
    }
}
