// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package citation.comm;


public class PostCitationEntry {
    protected int citationNumber;
    protected java.lang.String key;
    protected java.lang.String value;
    
    public PostCitationEntry() {
    }
    
    public PostCitationEntry(int citationNumber, java.lang.String key, java.lang.String value) {
        this.citationNumber = citationNumber;
        this.key = key;
        this.value = value;
    }
    
    public int getCitationNumber() {
        return citationNumber;
    }
    
    public void setCitationNumber(int citationNumber) {
        this.citationNumber = citationNumber;
    }
    
    public java.lang.String getKey() {
        return key;
    }
    
    public void setKey(java.lang.String key) {
        this.key = key;
    }
    
    public java.lang.String getValue() {
        return value;
    }
    
    public void setValue(java.lang.String value) {
        this.value = value;
    }
}
