// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package citation.comm;


public class GetDMVResultAsXMLResponse {
    protected java.lang.String getDMVResultAsXMLReturn;
    
    public GetDMVResultAsXMLResponse() {
    }
    
    public GetDMVResultAsXMLResponse(java.lang.String getDMVResultAsXMLReturn) {
        this.getDMVResultAsXMLReturn = getDMVResultAsXMLReturn;
    }
    
    public java.lang.String getGetDMVResultAsXMLReturn() {
        return getDMVResultAsXMLReturn;
    }
    
    public void setGetDMVResultAsXMLReturn(java.lang.String getDMVResultAsXMLReturn) {
        this.getDMVResultAsXMLReturn = getDMVResultAsXMLReturn;
    }
}
