// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package citation.comm;


public class OpenCitation {
    protected int citationNumber;
    
    public OpenCitation() {
    }
    
    public OpenCitation(int citationNumber) {
        this.citationNumber = citationNumber;
    }
    
    public int getCitationNumber() {
        return citationNumber;
    }
    
    public void setCitationNumber(int citationNumber) {
        this.citationNumber = citationNumber;
    }
}
