// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package citation.comm;


public class PostCitationAsXMLResponse {
    protected int postCitationAsXMLReturn;
    
    public PostCitationAsXMLResponse() {
    }
    
    public PostCitationAsXMLResponse(int postCitationAsXMLReturn) {
        this.postCitationAsXMLReturn = postCitationAsXMLReturn;
    }
    
    public int getPostCitationAsXMLReturn() {
        return postCitationAsXMLReturn;
    }
    
    public void setPostCitationAsXMLReturn(int postCitationAsXMLReturn) {
        this.postCitationAsXMLReturn = postCitationAsXMLReturn;
    }
}
