// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package citation.comm;


public class GetCourtInfoAsXMLResponse {
    protected java.lang.String getCourtInfoAsXMLReturn;
    
    public GetCourtInfoAsXMLResponse() {
    }
    
    public GetCourtInfoAsXMLResponse(java.lang.String getCourtInfoAsXMLReturn) {
        this.getCourtInfoAsXMLReturn = getCourtInfoAsXMLReturn;
    }
    
    public java.lang.String getGetCourtInfoAsXMLReturn() {
        return getCourtInfoAsXMLReturn;
    }
    
    public void setGetCourtInfoAsXMLReturn(java.lang.String getCourtInfoAsXMLReturn) {
        this.getCourtInfoAsXMLReturn = getCourtInfoAsXMLReturn;
    }
}
