// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package citation.comm;


public class PingResponse {
    protected int pingReturn;
    
    public PingResponse() {
    }
    
    public PingResponse(int pingReturn) {
        this.pingReturn = pingReturn;
    }
    
    public int getPingReturn() {
        return pingReturn;
    }
    
    public void setPingReturn(int pingReturn) {
        this.pingReturn = pingReturn;
    }
}
