// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package citation.comm;


public class PostStringResponse {
    protected int postStringReturn;
    
    public PostStringResponse() {
    }
    
    public PostStringResponse(int postStringReturn) {
        this.postStringReturn = postStringReturn;
    }
    
    public int getPostStringReturn() {
        return postStringReturn;
    }
    
    public void setPostStringReturn(int postStringReturn) {
        this.postStringReturn = postStringReturn;
    }
}
